spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rdbcalenda?useSSL=false
    username: root
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080

